version: '2'

services:
    web:
        build:
            context: ./images/snipeit
            args:
                - SNIPEIT_VERSION=${SNIPEIT_VERSION}
        image: ianharrier/snipeit:${SNIPEIT_VERSION}
        restart: unless-stopped
        ports:
            - ${WEB_PORT}:80
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - APP_URL=${WEB_APP_URL}
            - APP_TIMEZONE=${TIMEZONE}
            - APP_LOCALE=${WEB_APP_LOCALE}
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_DATABASE=${DB_MYSQL_DATABASE}
            - DB_USERNAME=${DB_MYSQL_USER}
            - DB_PASSWORD=${DB_MYSQL_PASSWORD}
            - MAIL_DRIVER=smtp
            - MAIL_HOST=${WEB_MAIL_HOST}
            - MAIL_PORT=${WEB_MAIL_PORT}
            - MAIL_USERNAME=${WEB_MAIL_USERNAME}
            - MAIL_PASSWORD=${WEB_MAIL_PASSWORD}
            - MAIL_ENCRYPTION=${WEB_MAIL_ENCRYPTION}
            - MAIL_FROM_ADDR=${WEB_MAIL_FROM_ADDR}
            - MAIL_FROM_NAME=${WEB_MAIL_FROM_NAME}
            - MAIL_REPLYTO_ADDR=${WEB_MAIL_REPLYTO_ADDR}
            - MAIL_REPLYTO_NAME=${WEB_MAIL_REPLYTO_NAME}
            - IMAGE_LIB=gd
            - APP_TRUSTED_PROXIES=${WEB_APP_TRUSTED_PROXIES}
        volumes:
            - ./volumes/web/data:/var/lib/snipeit:Z
    db:
        image: mysql
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_MYSQL_DATABASE}
            - MYSQL_USER=${DB_MYSQL_USER}
            - MYSQL_PASSWORD=${DB_MYSQL_PASSWORD}
        volumes:
            - ./volumes/db/data:/var/lib/mysql:Z
    scheduler:
        build:
            context: ./images/scheduler
            args:
                - GLIBC_VERSION=2.27-r0
                - COMPOSE_VERSION=1.19.0
        image: ianharrier/snipeit-scheduler:1.0.11
        restart: unless-stopped
        environment:
            - LDAP_SYNC_OPERATION=${WEB_LDAP_SYNC_OPERATION}
            - LDAP_SYNC_CRON_EXP=${WEB_LDAP_SYNC_CRON_EXP}
            - HOST_PATH=${PWD}
            - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
            - TIMEZONE=${TIMEZONE}
        volumes:
            - ./:${PWD}
            - /var/run/docker.sock:/var/run/docker.sock
        security_opt:
            - label:disable
    backup:
        build:
            context: ./images/backup
            args:
                - GLIBC_VERSION=2.27-r0
                - COMPOSE_VERSION=1.19.0
        image: ianharrier/snipeit-backup:1.0.11
        restart: unless-stopped
        environment:
            - OPERATION=${BACKUP_OPERATION}
            - CRON_EXP=${BACKUP_CRON_EXP}
            - RETENTION=${BACKUP_RETENTION}
            - HOST_PATH=${PWD}
            - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
            - TIMEZONE=${TIMEZONE}
        volumes:
            - ./:${PWD}
            - /var/run/docker.sock:/var/run/docker.sock
        security_opt:
            - label:disable
